apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-spring-boot-example.fullname" . }}
  labels:
    {{- include "java-spring-boot-example.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: {{ .Values.service.protocol }}
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    name: http
  selector:
    {{- include "java-spring-boot-example.selectorLabels" . | nindent 4 }}
