apiVersion: v1
kind: Service
metadata:
  name: java-spring-boot-example
  labels:
    app: java-spring-boot-example
spec:
  type: NodePort
  selector:
    app: java-spring-boot-example
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30080
